var search_data = [
    {"word" : "The Abyssinians"},
    {"word" : "The Aces"},
    {"word" : "Glen Adams"},
    {"word" : "Admiral T"},
    {"word" : "Yasus Afari"},
    {"word" : "African Brothers"},
    {"word" : "The Aggrovators"},
    {"word" : "Aisha"},
    {"word" : "Bobby Aitken"},
    {"word" : "Laurel Aitken"},
    {"word" : "Alaine"},
    {"word" : "Alborosie"},
    {"word" : "Dennis Alcapone"},
    {"word" : "Alozade"},
    {"word" : "Alpha & Omega"},
    {"word" : "Roland Alphonso"},
    {"word" : "Althea & Donna"},
    {"word" : "Al Anderson"},
    {"word" : "Lynford Anderson aka 'Andy Capp'"},
    {"word" : "Bob Andy"},
    {"word" : "Horace Andy"},
    {"word" : "Mike Anthony"},
    {"word" : "Patrick Andy"},
    {"word" : "Anthony B"},
    {"word" : "Apache Indian"},
    {"word" : "Marlon Asher"},
    {"word" : "Aswad"},
    {"word" : "Audio Active"},
    {"word" : "Baba Brooks"},
    {"word" : "Baby Cham"},
    {"word" : "Baby Wayne"},
    {"word" : "Bad Brains"},
    {"word" : "Admiral Bailey"},
    {"word" : "Spanner Banner"},
    {"word" : "Buju Banton"},
    {"word" : "Burro Banton"},
    {"word" : "Mega Banton"},
    {"word" : "Pato Banton"},
    {"word" : "Starkey Banton"},
    {"word" : "Dave Barker"},
    {"word" : "Aston Barrett"},
    {"word" : "Carlton Barrett"},
    {"word" : "Theophilus Beckford"},
    {"word" : "Bedouin Soundclash"},
    {"word" : "Beenie Man"},
    {"word" : "Nayanka Bell"},
    {"word" : "Lorna Bennett"},
    {"word" : "Spragga Benz"},
    {"word" : "Beshara"},
    {"word" : "Big Joe"},
    {"word" : "Big Mountain"},
    {"word" : "Big Youth"},
    {"word" : "Barry Biggs"},
    {"word" : "Black Roots"},
    {"word" : "The Black Seeds"},
    {"word" : "Black Slate"},
    {"word" : "The Blackstones"},
    {"word" : "Black Uhuru"},
    {"word" : "Everton Blender"},
    {"word" : "Alpha Blondy"},
    {"word" : "Blue Riddim Band"},
    {"word" : "The Blues Busters"},
    {"word" : "Yami Bolo"},
    {"word" : "Bongo Herman"},
    {"word" : "Barry Boom"},
    {"word" : "Ken Boothe"},
    {"word" : "Born Jamericans"},
    {"word" : "Bounty Killer"},
    {"word" : "Dennis Bovell aka Blackbeard"},
    {"word" : "Andru Branch"},
    {"word" : "Brick & Lace"},
    {"word" : "Annette Brissett"},
    {"word" : "Peter Broggs"},
    {"word" : "Cedric Brooks"},
    {"word" : "Mike Brooks"},
    {"word" : "Barry Brown"},
    {"word" : "Dennis Brown"},
    {"word" : "Foxy Brown"},
    {"word" : "Glen Brown"},
    {"word" : "Junior Brown"},
    {"word" : "Prezident Brown"},
    {"word" : "U Brown"},
    {"word" : "Buccaneer"},
    {"word" : "Burning Spear"},
    {"word" : "Bushman"},
    {"word" : "Busy Signal"},
    {"word" : "Junior Byles"},
    {"word" : "The Cables"},
    {"word" : "Susan Cadogan"},
    {"word" : "Al Campbell"},
    {"word" : "Cornell Campbell"},
    {"word" : "Don Campbell"},
    {"word" : "Martin Campbell"},
    {"word" : "Icho Candy"},
    {"word" : "Capleton"},
    {"word" : "Captain Sinbad"},
    {"word" : "Don Carlos"},
    {"word" : "Carlton and The Shoes"},
    {"word" : "Lacksley Castell"},
    {"word" : "Chalice"},
    {"word" : "The Chantells"},
    {"word" : "Charlie Chaplin"},
    {"word" : "Charly B"},
    {"word" : "Lloyd Charmers"},
    {"word" : "Tessanne Chin"},
    {"word" : "Tony Chin"},
    {"word" : "The Chosen Few"},
    {"word" : "Christafari"},
    {"word" : "Chronixx"},
    {"word" : "Geoffrey Chung"},
    {"word" : "Mikey Chung"},
    {"word" : "Tami Chynn"},
    {"word" : "Cidade Negra"},
    {"word" : "The Cimarons"},
    {"word" : "The Clarendonians"},
    {"word" : "Augustus Gussie Clarke"},
    {"word" : "Johnny Clarke"},
    {"word" : "Jimmy Cliff"},
    {"word" : "Cocoa Tea"},
    {"word" : "Stranger Cole"},
    {"word" : "Collie Buddz"},
    {"word" : "Ansell Collins"},
    {"word" : "The Congos"},
    {"word" : "Joseph Cotton"},
    {"word" : "Count Ossie"},
    {"word" : "Tommy Cowan"},
    {"word" : "Culcha Candela"},
    {"word" : "Cultura ProfÃ©tica"},
    {"word" : "Culture"},
    {"word" : "Daab"},
    {"word" : "Danny Red"},
    {"word" : "Daddy Freddy"},
    {"word" : "Daddy Screw"},
    {"word" : "Tonton David"},
    {"word" : "Da'Ville"},
    {"word" : "Ronnie Davis"},
    {"word" : "Nora Dean"},
    {"word" : "Desmond Dekker"},
    {"word" : "Del Arno Band"},
    {"word" : "Junior Delgado"},
    {"word" : "Chaka Demus & Pliers"},
    {"word" : "Dillinger"},
    {"word" : "Phyllis Dillon"},
    {"word" : "Dobby Dobson"},
    {"word" : "Eric Donaldson"},
    {"word" : "Dr Alimantado"},
    {"word" : "Tyrone Downie"},
    {"word" : "The Drastics"},
    {"word" : "Mikey Dread"},
    {"word" : "Don Drummond"},
    {"word" : "Dry & Heavy"},
    {"word" : "Dub FX"},
    {"word" : "Dub Incorporation"},
    {"word" : "Lucky Dube"},
    {"word" : "Sly Dunbar"},
    {"word" : "Errol Dunkley"},
    {"word" : "The Dynamites"},
    {"word" : "Earl Sixteen"},
    {"word" : "Echo Movement"},
    {"word" : "Clint Eastwood"},
    {"word" : "Easy Star All*Stars"},
    {"word" : "Clancy Eccles"},
    {"word" : "Jackie Edwards"},
    {"word" : "Rupie Edwards"},
    {"word" : "Eek a Mouse"},
    {"word" : "Elephant Man"},
    {"word" : "El General"},
    {"word" : "Alton Ellis"},
    {"word" : "Hortense Ellis"},
    {"word" : "Junior English"},
    {"word" : "The Ethiopians"},
    {"word" : "Earl Flute"},
    {"word" : "Etana"},
    {"word" : "Jermaine Fagan"},
    {"word" : "Tiken Jah Fakoly"},
    {"word" : "Majek Fashek"},
    {"word" : "Fathead"},
    {"word" : "Chuck Fenda"},
    {"word" : "Robert Ffrench"},
    {"word" : "Edi Fitzroy"},
    {"word" : "Sharon Forrester"},
    {"word" : "Dean Fraser"},
    {"word" : "Lutan Fyah"},
    {"word" : "Boris Gardiner"},
    {"word" : "The Gaylads"},
    {"word" : "General Echo"},
    {"word" : "General Levy"},
    {"word" : "General Trees"},
    {"word" : "Gentleman"},
    {"word" : "Sophia George"},
    {"word" : "The Gladiators"},
    {"word" : "Deborahe Glasgow"},
    {"word" : "Edson Gomes"},
    {"word" : "Vin Gordon"},
    {"word" : "Eddy Grant"},
    {"word" : "Rudy Grant"},
    {"word" : "Owen Gray"},
    {"word" : "The Green"},
    {"word" : "Winston Grennan"},
    {"word" : "Greyhound"},
    {"word" : "Marcia Griffiths"},
    {"word" : "Winston Groovy"},
    {"word" : "Groundation"},
    {"word" : "Gyptian"},
    {"word" : "Haha"},
    {"word" : "Half Pint"},
    {"word" : "Audrey Hall"},
    {"word" : "Beres Hammond"},
    {"word" : "Derrick Harriott"},
    {"word" : "Josh Heinrichs"},
    {"word" : "The Heptones"},
    {"word" : "Herbs"},
    {"word" : "Lennie Hibbert"},
    {"word" : "Joe Higgs"},
    {"word" : "Joseph Hill"},
    {"word" : "Justin Hinds"},
    {"word" : "The Hippy Boys"},
    {"word" : "Errol Holt"},
    {"word" : "John Holt"},
    {"word" : "Honey Boy"},
    {"word" : "Keith Hudson"},
    {"word" : "Peter Hunnigale"},
    {"word" : "Clive Hunt"},
    {"word" : "Sheila Hylton"},
    {"word" : "Ijahman Levi"},
    {"word" : "Inner Circle"},
    {"word" : "I-Roy"},
    {"word" : "IsmaÃ«l Isaac"},
    {"word" : "I-Threes"},
    {"word" : "The In Crowd"},
    {"word" : "Iration"},
    {"word" : "Tippa Irie"},
    {"word" : "Welton Irie"},
    {"word" : "Devon Irons"},
    {"word" : "Gregory Isaacs"},
    {"word" : "Israel Vibration"},
    {"word" : "The Itals"},
    {"word" : "I-Wayne"},
    {"word" : "Jah Cure"},
    {"word" : "Jah Lion aka Jah Lloyd"},
    {"word" : "Jah Roots"},
    {"word" : "Jah Shaka"},
    {"word" : "Jah Stitch"},
    {"word" : "Jah Woosh"},
    {"word" : "Jah Warrior"},
    {"word" : "David Jahson"},
    {"word" : "Winston Jarrett"},
    {"word" : "J.O.E."},
    {"word" : "Anthony Johnson"},
    {"word" : "Linton Kwesi Johnson"},
    {"word" : "Vivian Jones"},
    {"word" : "Judge Dread"},
    {"word" : "Katchafire"},
    {"word" : "Kalaeloa"},
    {"word" : "Janet Kay"},
    {"word" : "Ini Kamoze"},
    {"word" : "Junior Kelly"},
    {"word" : "Pat Kelly"},
    {"word" : "Kiddus I"},
    {"word" : "Diana King"},
    {"word" : "Jigsy King"},
    {"word" : "King Sounds"},
    {"word" : "King Stitt"},
    {"word" : "King Tubby"},
    {"word" : "Sean Kingston"},
    {"word" : "Knowledge"},
    {"word" : "Lady Saw"},
    {"word" : "Eric Bingy Bunny Lamont"},
    {"word" : "Byron Lee"},
    {"word" : "Barrington Levy"},
    {"word" : "Hopeton Lewis"},
    {"word" : "Aura Lewis"},
    {"word" : "Lieutenant Stitchie"},
    {"word" : "Little Hero"},
    {"word" : "Little John"},
    {"word" : "Little Kevin"},
    {"word" : "Little Roy"},
    {"word" : "Dandy Livingstone"},
    {"word" : "Jah Lloyd"},
    {"word" : "Fred Locks"},
    {"word" : "Locomondo"},
    {"word" : "June Lodge"},
    {"word" : "Jimmy London"},
    {"word" : "Lone Ranger"},
    {"word" : "Luciano"},
    {"word" : "Macka B"},
    {"word" : "Mad Cobra"},
    {"word" : "David Madden"},
    {"word" : "Mad Lion"},
    {"word" : "Mad Professor"},
    {"word" : "Mafia & Fluxy"},
    {"word" : "Magic!"},
    {"word" : "Carl Malcolm"},
    {"word" : "Bob Marley"},
    {"word" : "Damian Junior Gong Marley"},
    {"word" : "Julian Marley"},
    {"word" : "Ky-Mani Marley"},
    {"word" : "Rita Marley"},
    {"word" : "Stephen Marley"},
    {"word" : "Ziggy Marley"},
    {"word" : "Steven Lenky Marsden"},
    {"word" : "Larry Marshall"},
    {"word" : "Wayne Marshall"},
    {"word" : "Junior Marvin"},
    {"word" : "Jah Mason"},
    {"word" : "Massive Dread"},
    {"word" : "Matisyahu"},
    {"word" : "Matumbi"},
    {"word" : "Mavado"},
    {"word" : "The Maytals"},
    {"word" : "The Maytones"},
    {"word" : "Tommy McCook"},
    {"word" : "Freddie McGregor"},
    {"word" : "Freddie McKay"},
    {"word" : "Bitty McLean"},
    {"word" : "Enos McLeod"},
    {"word" : "The Mexicano"},
    {"word" : "Me & You"},
    {"word" : "Edge Michael"},
    {"word" : "Michigan & Smiley"},
    {"word" : "Midnite"},
    {"word" : "The Mighty Diamonds"},
    {"word" : "Mighty Mystic"},
    {"word" : "Mikey Dread"},
    {"word" : "Jacob Miller"},
    {"word" : "Millie"},
    {"word" : "Sugar Minott"},
    {"word" : "Mishka"},
    {"word" : "Misty in Roots"},
    {"word" : "Jackie Mittoo"},
    {"word" : "Fantan Mojah"},
    {"word" : "Derrick Morgan"},
    {"word" : "Morgan Heritage"},
    {"word" : "The Morwells"},
    {"word" : "Pablo Moses"},
    {"word" : "Judy Mowatt"},
    {"word" : "Mr. Vegas"},
    {"word" : "Hugh Mundell"},
    {"word" : "Junior Murvin"},
    {"word" : "Musical Youth"},
    {"word" : "Mutabaruka"},
    {"word" : "Cedric Myton"},
    {"word" : "Fidel Nadal"},
    {"word" : "Nando Boom"},
    {"word" : "Johnny Nash"},
    {"word" : "Natiruts"},
    {"word" : "Natural Black"},
    {"word" : "Nicodemus"},
    {"word" : "Nigger Kojak"},
    {"word" : "Ninjaman"},
    {"word" : "Nitty Gritty"},
    {"word" : "George Nooks"},
    {"word" : "No-Maddz"},
    {"word" : "Oku Onuora"},
    {"word" : "Opihi Pickers"},
    {"word" : "Jackie Opel"},
    {"word" : "O-Shen"},
    {"word" : "Johnny Osbourne"},
    {"word" : "Augustus Pablo"},
    {"word" : "Triston Palma"},
    {"word" : "Pan Head"},
    {"word" : "Papa Dee"},
    {"word" : "Papa San"},
    {"word" : "Paprika Korps"},
    {"word" : "The Paragons"},
    {"word" : "Ken Parker"},
    {"word" : "Lloyd Parks"},
    {"word" : "Frankie Paul"},
    {"word" : "Sean Paul"},
    {"word" : "Dawn Penn"},
    {"word" : "Pepper"},
    {"word" : "Lee Scratch Perry"},
    {"word" : "Pinchers"},
    {"word" : "Dwight Pinkney"},
    {"word" : "The Pioneers"},
    {"word" : "Pliers"},
    {"word" : "Jukka Poika"},
    {"word" : "Popcaan"},
    {"word" : "Maxi Priest"},
    {"word" : "Prince Allah"},
    {"word" : "Prince Buster"},
    {"word" : "Prince Far I"},
    {"word" : "Prince Jazzbo"},
    {"word" : "Prince Mohammed"},
    {"word" : "Michael Prophet"},
    {"word" : "Protoje"},
    {"word" : "The Pyramids"},
    {"word" : "Finley Quaye"},
    {"word" : "Queen Ifrica"},
    {"word" : "Queen Omega"},
    {"word" : "Raappana (musician)"},
    {"word" : "Ernest Ranglin"},
    {"word" : "Ranking Dread"},
    {"word" : "Ranking Joe"},
    {"word" : "Ranking Roger"},
    {"word" : "Cutty Ranks"},
    {"word" : "Gappy Ranks"},
    {"word" : "Shabba Ranks"},
    {"word" : "The Rastafarians"},
    {"word" : "Ras Michael"},
    {"word" : "Ras Midas"},
    {"word" : "Ras Shiloh"},
    {"word" : "Rayvon"},
    {"word" : "Tony Rebel"},
    {"word" : "Rebelution"},
    {"word" : "Red Dragon"},
    {"word" : "Red Rat"},
    {"word" : "Winston Reedy"},
    {"word" : "Junior Reid"},
    {"word" : "The Revolutionaries"},
    {"word" : "Rhythm & Sound"},
    {"word" : "Cynthia Richards"},
    {"word" : "Rihanna"},
    {"word" : "Jimmy Riley"},
    {"word" : "Tarrus Riley"},
    {"word" : "Winston Riley"},
    {"word" : "Johnny Ringo"},
    {"word" : "Rico Rodriguez"},
    {"word" : "Max Romeo"},
    {"word" : "Gene Rondo"},
    {"word" : "The Roots Radics"},
    {"word" : "Levi Roots"},
    {"word" : "Michael Rose"},
    {"word" : "The Royals"},
    {"word" : "The Rudies"},
    {"word" : "Bruce Ruffin"},
    {"word" : "Devon Russell"},
    {"word" : "Natasja Saad"},
    {"word" : "Samsâ€™K Le Jah"},
    {"word" : "Sanchez"},
    {"word" : "Scientist"},
    {"word" : "Errol Scorcher"},
    {"word" : "Scotty"},
    {"word" : "Screwdriver"},
    {"word" : "B.B. Seaton"},
    {"word" : "Seeed"},
    {"word" : "Serani"},
    {"word" : "Shaggy"},
    {"word" : "Bim Sherman"},
    {"word" : "Pluto Shervington"},
    {"word" : "Shinehead"},
    {"word" : "Roy Shirley"},
    {"word" : "Garnett Silk"},
    {"word" : "The Silvertones"},
    {"word" : "Simplicity"},
    {"word" : "Sister Carol"},
    {"word" : "Sister Nancy"},
    {"word" : "Sizzla"},
    {"word" : "Slightly Stoopid"},
    {"word" : "The Slickers"},
    {"word" : "Sly and Robbie"},
    {"word" : "Leroy Smart"},
    {"word" : "Smiley Culture"},
    {"word" : "Earl Chinna Smith"},
    {"word" : "Ernie Smith"},
    {"word" : "Mikey Smith"},
    {"word" : "Slim Smith"},
    {"word" : "Wayne Smith"},
    {"word" : "Snoop Lion, the stage name for Snoop Dogg's reggae projects"},
    {"word" : "Snow"},
    {"word" : "SOJA"},
    {"word" : "Soul Syndicate"},
    {"word" : "Soul Rebels Brass Band"},
    {"word" : "The Specials"},
    {"word" : "Spectacular"},
    {"word" : "Mikey Spice"},
    {"word" : "Richie Spice"},
    {"word" : "Steel Pulse"},
    {"word" : "Steely & Clevie"},
    {"word" : "Richie Stephens"},
    {"word" : "Tanya Stephens"},
    {"word" : "Lester Sterling"},
    {"word" : "Roman Stewart"},
    {"word" : "Tinga Stewart"},
    {"word" : "Super Cat"},
    {"word" : "Symarip"},
    {"word" : "Lynn Taitt"},
    {"word" : "The Tamlins"},
    {"word" : "Rod Taylor"},
    {"word" : "The Techniques"},
    {"word" : "The Tennors"},
    {"word" : "Tenor Saw"},
    {"word" : "Tiger"},
    {"word" : "Third World"},
    {"word" : "Jah Thomas"},
    {"word" : "Nicky Thomas"},
    {"word" : "Caroll Thompson"},
    {"word" : "Kemar Thompson (aka Noncowa, aka Jr. Pinchers)"},
    {"word" : "Lincoln Thompson"},
    {"word" : "Linval Thompson"},
    {"word" : "Eddie Thornton aka 'Tan Tan'"},
    {"word" : "T.O.K."},
    {"word" : "Tomorrows Bad Seeds"},
    {"word" : "Toots & the Maytals"},
    {"word" : "Andrew Tosh"},
    {"word" : "Peter Tosh"},
    {"word" : "Toyan"},
    {"word" : "Tradition"},
    {"word" : "Tribal Seeds"},
    {"word" : "Tribo de Jah"},
    {"word" : "Trinity"},
    {"word" : "Junior Tucker"},
    {"word" : "Twinkle Brothers"},
    {"word" : "UB40"},
    {"word" : "The Uniques"},
    {"word" : "Unity Pacific"},
    {"word" : "The Upsetters"},
    {"word" : "U-Roy"},
    {"word" : "Vavamuffin"},
    {"word" : "Vibronics"},
    {"word" : "The Viceroys"},
    {"word" : "Romain Virgo"},
    {"word" : "Voice Mail"},
    {"word" : "Vybz Kartel"},
    {"word" : "Wayne Wade"},
    {"word" : "Bunny Wailer"},
    {"word" : "The Wailers (Bob Marley & The Wailers)"},
    {"word" : "The Wailing Souls"},
    {"word" : "Josey Wales"},
    {"word" : "Leroy Wallace"},
    {"word" : "Ward 21"},
    {"word" : "E.T. Webster"},
    {"word" : "Caron Wheeler"},
    {"word" : "Worl-A-Girl"},
    {"word" : "Willi Williams"},
    {"word" : "Delroy Wilson"},
    {"word" : "Wingless Angels"},
    {"word" : "Wayne Wonder"},
    {"word" : "Word, Sound and Power"},
    {"word" : "Winston Wright"},
    {"word" : "Yabby You"},
    {"word" : "Yellowman"},
    {"word" : "Zap Pow"},
    {"word" : "Benjamin Zephaniah"},
    {"word" : "Earl Zero"},
    {"word" : "Zox"},
    {"word" : "Tapper Zukie"}
]

export default search_data